kube-prometheus-stack:
  grafana:
    adminPassword: argo-demo
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        ArgoCD:
          url: https://raw.githubusercontent.com/argoproj/argo-cd/master/examples/dashboard.json