kube-prometheus-stack:
  alertmanager:
    ingress:
      enabled: true
      hosts:
        - alertmanager.localhost
      paths:
        - /
  grafana:
    adminPassword: admin
    sidecar:
      dashboards:
        enabled: true
        labelValue: ""
    ingress:
      enabled: true
      hosts:
        - grafana.localhost
      paths:
        - /
  prometheus:
    ingress:
      enabled: true
      hosts:
        - prometheus.localhost
      paths:
        - /
    prometheusSpec:
      scrapeInterval: 10s

