apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  source:
    path: infra/monitoring/kube-prometheus-stack
    repoURL: https://github.com/34fathombelow/argocd-prometheus-demo.git
    targetRevision: main
  destination:
    namespace: monitoring
    server: 'https://kubernetes.default.svc'
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true