apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-not-synced
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: guestbook-notsynced
    server: 'https://kubernetes.default.svc'
  source:
    path: guestbook
    repoURL: https://github.com/34fathombelow/argocd-prometheus-demo.git
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true