apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-dragonfly-db
  namespace: argocd
  labels:
    group: dragonfly
    app: argocd-dragonfly-db
    release: kube-prometheus-stack
    
spec:
  selector:
    matchLabels:
      app: argocd-dragonfly-db
  podTargetLabels:
    - app
  podMetricsEndpoints:
  - port: admin
