apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  namespace: argocd
spec:
  selfSigned: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-dragonfly-password
  namespace: argocd
type: Opaque
stringData:
  password: '12345678'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-dragonfly-cert
  namespace: argocd
spec:
  secretName: dragonflydb-tls
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
      - dragonfly-sample
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - argocd-dragonflydb.argocd
    - argocd-dragonflydb
    - argocd-dragonfly-db
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly-sample
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dragonfly-operator
  namespace: argocd
  name: argocd-dragonfly-db
spec:
  args:
    - "--proactor_threads=1"
    - "--maxmemory=1GiB"
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.23.1
  # Password authentication needed when TLS enabled
  authentication:
      passwordFromSecret:
        name: argocd-dragonfly-password
        key: password
  tlsSecretRef:
      name: dragonflydb-tls
  replicas: 2
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: dragonfly
          topologyKey: kubernetes.io/hostname
      - weight: 5
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/part-of: argocd
          topologyKey: kubernetes.io/hostname


  resources:
    requests:
      cpu: 500m
      memory: 50Mi
    limits:
      cpu: 600m
      memory: 750Mi