apiVersion: dragonflydb.io/v1alpha1
kind: Dragonfly
metadata:
  labels:
    app.kubernetes.io/name: dragonfly
    app.kubernetes.io/instance: dragonfly-sample
    app.kubernetes.io/part-of: dragonfly-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: dragonfly-operator
  namespace: argocd
  name: argocd-dragonfly-db
spec:
  args:
    - "--proactor_threads=1"
    - "--compression_mode=2"
    - "--compression_level=2"
  image: docker.dragonflydb.io/dragonflydb/dragonfly:v1.13.0
  replicas: 2
  resources:
    requests:
      cpu: 500m
      memory: 50Mi
    limits:
      cpu: 600m
      memory: 750Mi