apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- resources/upstream.yaml
- monitoring-config/argocd-api-server-metrics-servicemonitor.yaml
- monitoring-config/argocd-applicationset-metrics-servicemonitor.yaml
- monitoring-config/argocd-controller-metrics-servicemonitor.yaml
- monitoring-config/argocd-repo-server-metrics-servicemonitor.yaml
- monitoring-config/prometheus-argocd-rules.yaml
