apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
images:
- name: quay.io/argoproj/argocd
  newName: quay.io/akuity/argocd
  newTag: v2.9.9-ak.22
resources:
- github.com/argoproj/argo-cd//manifests/base/application-controller?ref=v2.9.3
- github.com/argoproj/argo-cd//manifests/base/dex?ref=v2.9.3
- github.com/argoproj/argo-cd//manifests/base/repo-server?ref=v2.9.3
- github.com/argoproj/argo-cd//manifests/base/server?ref=v2.9.3
- github.com/argoproj/argo-cd//manifests/base/config?ref=v2.9.3
- github.com/argoproj/argo-cd//manifests/base/notification?ref=v2.9.3
- github.com/argoproj/argo-cd//manifests/base/applicationset-controller?ref=v2.9.3
- github.com/argoproj/argo-cd//manifests/cluster-rbac?ref=v2.9.3
- github.com/argoproj/argo-cd//manifests/crds?ref=v2.9.3
- overlays/production/argocd-dragonfly-db.yaml
- overlays/production/ingress-route.yaml


patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-server
    spec:
      template:
        spec:
          initContainers:
            - name: extension-metrics
              image: quay.io/argoprojlabs/argocd-extension-installer:v0.0.1
              env:
              - name: EXTENSION_URL
                value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.3/extension.tar
              volumeMounts:
                - name: extensions
                  mountPath: /tmp/extensions/
              securityContext:
                runAsUser: 1000
                allowPrivilegeEscalation: false
  target:
    kind: Deployment
    name: argocd-server
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: argocd-server
    spec:
      template:
        spec:
          containers:
            - name: argocd-server
              volumeMounts:
                - name: extensions
                  mountPath: /tmp/extensions/
          volumes:
            - name: extensions
              emptyDir: {}
  target:
    kind: Deployment
    name: argocd-server
- path: overlays/production/argocd-cm.yaml
- path: overlays/production/argocd-rbac-cm.yaml
- path: overlays/production/argocd-cmd-params-cm.yaml
- path: overlays/production/argocd-server.yaml
- path: overlays/production/argocd-application-controller.yaml
- path: overlays/production/argocd-repo-server.yaml
