apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
- github.com/argoproj/argo-cd/manifests/base?ref=v2.8.2

patchesStrategicMerge:
- overlays/production/argocd-cm.yaml
- overlays/production/argocd-rbac-cm.yaml
- overlays/production/argocd-cmd-params-cm.yaml

